# Distant properties

spring:
  application:
    name: lootopia-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}
  session:
    jdbc:
      initialize-schema: always

logging:
  level:
    web: DEBUG
    org.springframework.security: DEBUG

mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  domain: ${MAIL_DOMAIN}
  password: ${MAIL_PASSWORD}

cors:
  allowed-origins: https://lootopia-client.azurewebsites.net