name: Build, test and deploy lootopia mobile client

on:
  push:
    branches:
      - main
  #pull_request:
  #  branches:
  #    - main
  workflow_dispatch:

defaults:
  run:
    working-directory: client-mobile

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: client-mobile/package-lock.json

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: client-mobile/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('client-mobile/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Save node_modules
        if: success()
        uses: actions/cache@v4
        with:
          path: client-mobile/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('client-mobile/package-lock.json') }}

  lint:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: client-mobile/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('client-mobile/package-lock.json') }}

      - name: Lint code
        run: npm run lint

  unit:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: client-mobile/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('client-mobile/package-lock.json') }}

      - name: Run unit tests
        run: npm run test

  build:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: client-mobile/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('client-mobile/package-lock.json') }}

      - name: Build mobile client
        run: npm run build

      - name: Archive ios build
        uses: actions/upload-artifact@v4
        with:
          name: ios
          path: client-mobile/ios
