name: Build, test and deploy lootopia server

on:
  push:
    branches:
      - main
  #pull_request:
  #  branches:
  #    - main
  workflow_dispatch:

defaults:
  run:
    working-directory: server

jobs:
  unit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "microsoft"

      - name: Test with Maven
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_SECURITY_USERNAME: ${{ secrets.SPRING_SECURITY_USERNAME }}
          SPRING_SECURITY_PASSWORD: ${{ secrets.SPRING_SECURITY_PASSWORD }}
        run: mvn test -D spring.profiles.active=local -f pom.xml

  build-and-push:
    runs-on: windows-latest
    needs: unit
    permissions:
      contents: read #This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "microsoft"

      - name: Build with Maven
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_SECURITY_USERNAME: ${{ secrets.SPRING_SECURITY_USERNAME }}
          SPRING_SECURITY_PASSWORD: ${{ secrets.SPRING_SECURITY_PASSWORD }}
        run: mvn clean install -D spring.profiles.active=distant -X

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: "${{ github.workspace }}/server/target/*.jar"

  deploy:
    runs-on: windows-latest
    needs: build-and-push
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: server

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C234C6EFE4284E85B2EDC1A4BC5DBC97 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EFD59D464C394553ABCE1FE2685B583A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6AFE8C394210428BBCE69EE7B62767A0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "lootopia-server"
          slot-name: "Production"
          package: "*.jar"
